
spring:
  batch:
    job:
      enabled: true
      names: ${job.name:NONE}
    jdbc:
      initialize-schema: always

#  quartz:
#    jdbc:
#      initialize-schema: always
#      #      schema: classpath:quartz-create.sql
#    scheduler-name: MyScheduler
#    job-store-type: jdbc
#    overwrite-existing-jobs: true
#    properties:
#      org:
#        quartz:
#          jobStore:
#            isClustered: true
#            useProperties: true




  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true


  datasource:
    url: jdbc:mysql://localhost:3306/batch?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver


